### PR TITLE
Adding TPascalSecond and TKilogramPerSecond ...

### PR DESCRIPTION
**Pull request by melchiorrecaruso**
Adding TPascalSecond and TKilogramPerSecond
Adding specific-weight class
Adding square speed class, adding alternative joule definition.

### CODE REVIEW

**Comment by circular17** [comment]
Hi!

I suppose you meant a division there?
```pascal
operator *(const {%H-}m2: TSquareMeterIdentifier; const {%H-}s2: TSquareSecondIdentifier): TSquareMeterPerSquareSecondIdentifier; inline;

operator *(const ASquareLength: TSquareMeters; const ASquareTime: TSquareSeconds): TSquareMetersPerSquareSecond; inline;
```

**Comment by melchiorrecaruso** [comment]
Yes, It Is. I'm fixing It.

**Comment by melchiorrecaruso** [comment]
Today, I'm unlucky. I can't fix it because the same operator already exists:

`operator /(const {%H-}m2: TSquareMeterIdentifier; const {%H-}s2: TSquareSecondIdentifier): TSievertIdentifier; inline;`
`operator /(const AArea: TSquareMeters; const ASquareTime: TSquareSeconds): TSieverts; inline;`

**Comment by circular17** [comment]
Ah indeed, the units already exists in fact. Well then, I suppose there is no need to define a new unit there. Or is there?

**Comment by melchiorrecaruso** [comment]
It's no need, I can replace it with Sievert. A little problem remains, the unit of a square speed is Sievert instead of m2/s2.
There is the same problem with J (energy) and Nm (torque).

**Comment by circular17** [comment]
If the display of m2/s2 is a problem, a way to solve this would be to rename the current Sievert unit and stop doing the automatic naming of it so that it would be displayed as m2/s2, and then add the Sievert as a new unit (like the Becquerel) with an equivalence with m2/s2. So to get a value in Sievert from square meters and square seconds you would have to write `Sv.From(squareMeters/squareSeconds)`

**Comment by melchiorrecaruso** [comment]
I have done something like that.

**Comment by circular17** [comment]
Ok. That doesnt work exactly like that as there is a duplicate for the definition of J/kg being equal to Sv and Gy.

I am not sure which one is more the real definition of it, though from what I seem to understand, Gy, the absorbed dose, is the most immediate unit from J / kg. Then Sv is derived from that by applying a factor.

And Gy and Sv and m2/s2 are the same SI units. So I suggest the following:
- Gy defined J/kg
- Sv defined as a new unit
- m2/s2 defined as m2/s2 (just the plain definition of it)

As automatic conversion is provided towards SI unit, then:
- an operator := to convert Gy to m2/s2
- an operator := to. convert Sv to m2/s2

And explicit conversions "From" using a helper:
- to convert from m2/s2 to Gy
- to convert from m2/s2 to Sv

What do you think?

**Comment by melchiorrecaruso** [comment]
Ok, Sievert can be a new unit, but it's missing the operator for assigning  a value. This operator already exists but it's used for Gray.

**Comment by circular17** [comment]
In theory, it is not a problem to have multiple operators := with the same parameter. The destination value determines which operator to use.

In the first place, I added operators in all directions, but sometimes this can cause places were it is not clear which one to use. For example, if you have m / h, we could convert m to km to get km/h, or we could convert h to s to have m/s.

To avoid this, I have privileged one direction, towards SI units. So if you write m / h, it is the conversion from h to s that is applied.

In the case of Gy, Sv and m2/s2, we can choose a direction for conversions: Sv -> Gy (=J/kg) -> m2/s2. If we want to go the other way, then we need to explicitly cast, by writing for example `Sv.From(squareMetersPerSquareSeconds)`.

There are some cases where conversion in both direction won't cause any undetermined situation, for example between `TKilograms` and `TBaseKilograms`.

**Comment by melchiorrecaruso** [comment]
I suppose I was not clear.

SievertVar := 10*(J/kg); // this doesn't compile because the result of J/kg operator is Gray only;

It's needed add an equivalence between Gray and Sievert.

I apologize, I haven't knowledge for understanding your explanation. Probably I will cancel the pull request.

**Comment by circular17** [comment]
There is no rush to cancel, you can take your time.

Regarding your example, because the conversion is in the reverse direction, then it would be written as:
```pascal
SievertVar := Sv.From(10*(J/kg));
```
Or in this case, as we have the value:
```pascal
SievertVar := 10*Sv;
```

**Comment by melchiorrecaruso** [comment]
I didn't understand the reason to have a unit like sievert if It's can't be used for making calculations.

**Comment by circular17** [comment]
Well il can be used to make computations. If you multiply a quantity in Sv by kilograms it will give you joules.

**Comment by melchiorrecaruso** [comment]
It's right, It works. I think that I have understood what you want to do and made suitable changes. Waiting for merging, I'm checking for next unit, but It's needed to define criteria about to how write math expression. Suppose we want to calculate thermal conduction, the expression is

Q/t = -k x A (dT/L)

fcl

where k is [W/m/K]. This expression can be wrote in different ways and for eatch way different mixed units are needed. 
For example:

Q/t = -k ((A x dT) / L);
Q/t = -k x A x dT / L;
...
Q/t = -k / L x A x dT;

We can choose to solve the most common expression only. 
We can choose to solve the expression without parentheses.
...

What do you think about that ?

EDIT: A rule can be to allow operations for returning to base unit only.

**Comment by circular17** [comment]
I think the code is ok to merge. I will look in more details to confirm that.

I understand your question about how to write the expressions. There can be many intermediate units.

What I would hope is that there is way to write so that intermediate results are in a unit that makes sense, that could be a result in itself. And so it could be needed to add brackets in order to have that.

In the example, does `k * A` mean something?  and `k * A * dT`? What about `dT / dL`?

**Comment by melchiorrecaruso** [comment]
`k * A` is `[W * m / K]`. I don't know if it is a unit of a physical entity. `dT / L` is a sort of temperature gradient.
Some infomations are here, see "Thermal resistance" section: [https://en.wikipedia.org/wiki/Thermal_conductivity](https://en.wikipedia.org/wiki/Thermal_conductivity).

EDIT1: I have a question: How do you think we will assign a value to k ? In this way
`k := 0.6 *(W/m/K); `or 
`k := 0.6 * W_mK; // with an identifier` 
or in both ways ?

~~EDIT2: Anyway it's needed to come back to initial values of k, A, dT and L from W, so all operators an intermediate units are needed. Merging units doesn't change this. Or am I wrong ?~~

**Comment by circular17** [comment]
I suppose making an identifier for the coefficient k doesn't really avoid the other units in the sense that this coefficient could be computed from the other values. Also `W_mK` is not very readable, it looks like millikelvins.

`dT / L` seems to be something, so I suppose it would be something like:
`dQ = -k * A * (dT / L)`

The `[W * m / K]` unit for `k * A` seems not obvious to avoid, so I suppose we need to add it anyway, even if it will not be used explicitely.

**Comment by circular17** [comment]
The following operator is in contradiction with the definition of the Gray unit, so I will remove it.

```pascal
operator /(const {%H-}J: TJouleIdentifier; const {%H-}kg: TKilogramIdentifier): TSquareMeterPerSquareSecondIdentifier; inline;
```

**Comment by circular17** [comment]
https://github.com/circular17/DimPas/commit/6ef5a11974f7767a9d782c439108dfdbb24882b6

**Comment by melchiorrecaruso** [comment]
> The following operator is in contradiction with the definition of the Gray unit, so I will remove it.

ok, it's true.

**Comment by melchiorrecaruso** [comment]
> I suppose making an identifier for the coefficient k doesn't really avoid the other units in the sense that this coefficient could be computed from the other values. Also W_mK is not very readable, it looks like millikelvins.

I agree. This can be a start point.
For assigning a value to `k` we need `W / m`, `W / K`, `m * k` and ` W / (m * k) ` classes and 
operators for `(W / K) / m` and `(W / m) / K`.
`k = [W / m / K]` can be the top class, you can mix units but nerver exceed the top class; so we can reorder the expression in this way `Q = k * dT * (A/L)`.
So other units aren't needed. I don't know if this can be reasonable and clear expecially for an user.

**Comment by circular17** [comment]
I understand, it makes sense, though I suppose it is indeed not very obvious for users.

It seems that the unit `[W / m2]` makes sense:
https://fr.wikipedia.org/wiki/Conductivit%C3%A9_thermique

Using it would rearrange the formula like as `Q = -k * (dT / L) * A`

Unit-wise that would be `[W]` = `[W / (m*K)]` * `[K / m]` * `[m2]`

So we need that `[W / (m*K)]` * `[K / m]` = `[W / m2]`. This could be replaced by:
`[(W / m2) / (K / m)]` * `[K / m]` = `[W / m2]`.

This could be done with a unit equivalence between `[(W / m2) / (K / m)]` and the unit of k `[W / (m*K)]` or `[W / m / K]`.

**Comment by melchiorrecaruso** [comment]
About the last point when you write equivalence, do you mean / and * operators ?  Then there are the classes to create `k` from `[W]`. Is it correct?

**Comment by circular17** [comment]
By equivalence I mean the `:=` operator. It allows to assign a value from one unit to the other.

Then k can be created as any of the units equivalent to `[W / (m*K)]`

**Comment by melchiorrecaruso** [comment]
Well, I haven't understood where is the equivalence.
I see TRatioUnit classes and an alternative definition.
Classes are:
`[W]/[m]/[K]=[W/m]/[K]=[W/(m*k)] `
`[W]/[m2]=[W/m2]`
`[K]/[m]=[K/m]`
and the alternative definition is
`[W/(m*k)] = [W/m2]\[K/m].`

**Comment by circular17** [comment]
What I wanted to say is that we could define `[(W/m2)/(K/m)]` as a unit, as a ratio unit of `[W/m2]`/`[K/m]` and then add an equivalence operator `:=` between `[W/(m*k)]` and `[(W/m2)/(K/m)]`. It has the advantage of limiting errors when it comes to defining the various operators.

But indeed we could do an alternative definition as you say. In this case, the operators for the alternative definition are added. That's what we've done so far, for example for `[V]` = `[W]` / `[A]`. It has the advantage of handling factored units: if we define a factored unit `[mW/(m*k)]` as the TMilliUnit of `[W/(m*k)]`, it can still be used with the alternative operators.

In contrast, when using the TMilliUnit with `[(W/m2)/(K/m)]`, to allow for the implicit conversion one would need to explicitly convert to base unit:
`Q = -millik.ToBase * (dT / L) * A`

With alternative definition operators, one can write:
`Q = -millik * (dT / L) * A`

What do you prefer?

**Comment by melchiorrecaruso** [comment]
I prefer alternative definition by operators rather than "alternative" class, but I will try it.
Btw, my problem is to check operators; checking could be easier if parameter names were generics (like ALeft, ARight...). 
But I suppose there is a reason for that.

About `[W/m/k]`, classes for building it are `[W/m]`, `[W/K]`, `[m/K]`, `[W/(m*K)]`, 
plus two alternative definitions `[[W/m]/[K]]` and `[[W/K]/[m]]`.

Then there are `[W/m2]` and `[K/m]` classes plus an alternative definition `[[W/m2]/[K/m]]`.
Result: six new classes plus three alternative definitions.

Are you agree ?

EDIT: I'm writing a tool for creating code, in this way I think to minimize errors and have a speed up.

EDIT2: Attached a draft.
[dim.zip](https://github.com/circular17/DimPas/files/11008873/dim.zip)

EDIT3: Attached a draft with equivalences.
[dim-2.zip](https://github.com/circular17/DimPas/files/11009746/dim-2.zip)

**Comment by circular17** [comment]
The only reason for naming the parameters is to provide meaning but it is not necessary. Also thinking about it we may be able replace all the operator codes by includes because for most of them only the parameter names and types change.

We may be reaching the maximum we can do without code generation. I will look at the zips when I get home.

Regards

**Comment by melchiorrecaruso** [comment]
Dear Circular,

you haven't replied to last post so I've supposed you are no longer interested in this project or too much busy with work, family or other.
So, I've stopped my pull requests and worked on my alternative dimpas project only, continuing to add new units.

I just want to let you know this.
Regards

**Comment by circular17** [comment]
Hi! Oh I realize I forgot about it. In fact, I was thinking I was waiting for your answer.

I have been doing other things, in fact not programming, but not to the point of not being to give you any answer. Sorry about that.

**Comment by circular17** [comment]
So looking at the code, it becomes difficult to check for errors and involves either code generation or copy and paste. We could do multiple files, though that would still be a lot of lines.

We may be able to add this formula, but I believe a new approach is needed. I would like to avoid code generation, so maybe using more macros.

**Comment by melchiorrecaruso** [comment]
I agree, can you write an example using  macro ? I'm not sure that the code will be more readable. 

Don't worry for missed reply.

**Comment by circular17** [comment]
Thanks for your understanding.

Agreed, I am not sure either macros are a solution for this either. I am trying out things.

**Comment by circular17** [comment]
Ok I've found a way to make things a bit simpler. I'm half way through.

**Comment by melchiorrecaruso** [comment]
Good new, thanks for updating.

**Comment by circular17** [comment]
Dear Melchiorrecaruso,

I've reorganized the code and add macros to define operators. I invite you to have a look and to tell me if all makes sense.

It is now much less prone to errors. So now using alternative definitions instead of classes is alright.

**Comment by melchiorrecaruso** [comment]
Great! You have done a lot of work. Thanks very much. 

I'm reading the code and I think that $[m^2/s^2] = [m^2] / [s^2]$ is missing:
`{$DEFINE NumId:=TSquareMeterId}{$DEFINE DenomId:=TSquareSecondId}{$DEFINE RatioId:=TSquareMeterPerSquareSecondId}
{$DEFINE NumQty:=TSquareMeters}{$DEFINE DenomQty:=TSquareSeconds}{$DEFINE RatioQty:=TSquareMetersPerSquareSecond}
{$DEFINE DEF_RATIO}{$i dim.pas} // m2/s2 = m2 / s2`

Anyway, It can be fixed later, I will look at new units before making changments. 
Thanks again, Regards

**Comment by circular17** [comment]
Thanks, you're very welcome. Indeed, that was quite some work. I am glad it is done.

You're right, this definition was missing. I've just added it.

Ok I let you read the code and think about the changes you would like to do.

Regards

**Comment by melchiorrecaruso** [comment]
I'm looking at $[Gy] = [ J/kg ] = [m^2/s^2]$ definitions and I have found these rows:
```
{$DEFINE NumId:=TJouleId}{$DEFINE DenomId:=TKilogramId}{$DEFINE RatioId:=TGrayId}
{$DEFINE NumQty:=TJoules}{$DEFINE DenomQty:=TKilograms}{$DEFINE RatioQty:=TGrays}
{$DEFINE DEF_RATIO}{$i dim.pas} // Gy = J / kg     
```
```
// alternate definitions
{$DEFINE LeftId:=TKilogramId}{$DEFINE RightId:=TSquareMeterPerSquareSecondId}{$DEFINE ProdId:=TJouleId}
{$DEFINE LeftQty:=TKilograms}{$DEFINE RightQty:=TSquareMetersPerSquareSecond}{$DEFINE ProdQty:=TJoules}
{$DEFINE ALT_PROD}{$i dim.pas} // J = kg * m2/s2  
``` 
In this case, isn't there a double operator definition ?  
I have already fallen in this trap.

My proposal is to create Gray as a new unit (the same way used for Sievert).
If you agree I will do some tests.

Regards

**Comment by circular17** [comment]
It's not a double definition. If it were, the compiler would complain.

Gray and Sievert are equivalent to [m2/s2] but not the same thing:
```pascal
// dimension equivalence
operator:=(const AEquivalentDose: TSieverts): TSquareMetersPerSquareSecond; inline;
{$IFDEF IMPL}begin result.Value := AEquivalentDose.Value; end;{$ENDIF}

operator:=(const AAbsorbedDose: TGrays): TSquareMetersPerSquareSecond; inline;
{$IFDEF IMPL}begin result.Value := AAbsorbedDose.Value; end;{$ENDIF} 
```

They are automatically convertible into [m2/s2] but not the other way around.

You can though make Gray and Sievert values from [m2/s2]:
```pascal
{ TGrayHelper }

function TGrayHelper.From(const ASquareSpeed: TSquareMetersPerSquareSecond): TGrays;
begin result.Value := ASquareSpeed.Value; end;

{ TSievertHelper }

function TSievertHelper.From(const ASquareSpeed: TSquareMetersPerSquareSecond): TSieverts;
begin result.Value := ASquareSpeed.Value; end; 
```

They way Gray is defined means that if one dived joules by kilograms, it will be expressed by default as Gray.
```pascal
type
  TGrayId = specialize TRatioUnitId<TJoule, TBaseKilogram>;
  TGrays = specialize TRatioQuantity<TJoule, TBaseKilogram>; 
```

There is no need to define Gray as a separate unit unless we want to prevent [J/kg] being equal by default to [Gy].

**Comment by melchiorrecaruso** [comment]
ok, but the code `gray_dose := 10*(J/kg);` doesn't work; 

Isn't it stange ?

**Comment by circular17** [comment]
Oh I see. I missed that. The problem is that the definition J = kg * m2/s2 includes the definition of J / kg = m2/s2. So there is indeed a double definition here. I am surprised the compiler did not complain. Maybe because the result type is not the same.

I've fixed it by adding an option not to implement the division by the "left" unit.

**Comment by melchiorrecaruso** [comment]
ALT_RATIO macro isn't defined... ok I can use ALT_PROD ... but without ALT_RATIO I can't put always the defined unit in the head.

For example, $rad/s$ definition will be:
- main definition $[rad/s] = [rad] / [s]$
- alternative definition $[m/s]=[rad/s] · [m]$

What do you think about that?

**Comment by circular17** [comment]
Yes. On the one hand it would be convenient to define a ratio, on the other hand a product seems simpler. I don’t mind if you want to add ALT_RATIO or rearrange the order of defines. For example instead of Left Right Product to have Product Left Right

**Comment by melchiorrecaruso** [comment]
It's needed define the ratio otherwise I can't put alternative definitions in the right place.

For example: the expression $[N / m3] = [ Pa ] / [ m ]$ as product becomes 
$[ Pa ] = [N / m3] * [ m ]$ but I can't put this definition next $[ Pa ]$ because
$[ N/m^3 ]$ is defined in the last .inc file included (special derived unit). 

Bye

**Comment by circular17** [comment]
Would you like me to write the ratio define or are you up to it?

**Comment by melchiorrecaruso** [comment]
Yes I'm, I will add it.

**Pull request merged**
