### PR TITLE
Adding electromagnetic fields units.

### PR DESCRIPTION
**Pull request by melchiorrecaruso**
Some alternative definition aren't in the right place.
It is needed choose a new criteria for ordering the units.

### CODE REVIEW

**Comment by circular17** [comment]
Good morning Melchiorrecaruso,

Changes merged. Are there other reordering that you would suggest, apart from what was in the pull request?

You seem to prefer to put the comment before rather than on the line of the include. Pros: it is a bit clearer, cons: it takes one more line. That's a detail though.

**Comment by melchiorrecaruso** [comment]
Hello circular,

it's needed move radiant and steradiant to top of derived unit, angular speed and angular acceleration after straight acceleration. this is the most important change. I will look it.

Have a nice day.

**Comment by circular17** [comment]
I think I understand. Initially I’ve put radian and steradian in special units as this is what the Wikipedia page suggested. Though if there is a practical reason they can be moved.

**Comment by melchiorrecaruso** [comment]
I put angular speed and acceleration in a wrong place. 
It is enough to move these from specialderived.inc to specialunit.inc and 
then I can uncomment for alternative definition

$[ W ] = [ J ] * [ rad/s ]$

No other moving are needed at the moment.
I will do that with next pull request.

**Comment by circular17** [comment]
Ok. Sounds ok to me.

Have good evening

**Pull request merged**
