### PR TITLE
Adding TSquareVolt and TSquareAmpere classes

### PR DESCRIPTION
**Pull request by melchiorrecaruso**
Adding TSquareVolt and TSquareAmpere classes.
It's needed to have a Sqrt (and Sqr) function for returning to base unit, I have wrote an Helper, please check it.

Are there already Helpers for Square, Cubic... units ?
I haven't found them.

### CODE REVIEW

**Comment by circular17** [comment]
Hmmm, I would rather define V2 and A2 as square units of V and A. Otherwise, it would not be equivalent to V * V and A * A. In theory then, Sqrt could be added automatically. There isn't any helper yet, it could be a way to go around the limitation of the class operators/functions. I will look into it.

It is possible on other other hand to add explicitly operators to combine W and Ω to give V2 and A2 results.

**Comment by circular17** [comment]
I've considered the following theoretical solution :

- forward declaration of records
- generic type helpers
- independent generic functions

But none of them are possible with current FPC.

Finally I found a way, but that requires to write the result unit:
```pascal
  writeln('The side of a 2 m2 surface is ', m.SquareRoot(2*m2).ToString);
  writeln('A cube of volume ', volume.ToString,
    ' has a side of ', m.CubicRoot(volume).ToString); 
```

I've commited this change: https://github.com/circular17/DimPas/commit/c36eb47b773e40b78c4c31ddcc7037a433fbea82

**Comment by melchiorrecaruso** [comment]
Ok, I will change A2 and V2 definition.

**Comment by circular17** [comment]
Also when defining A2 as the square of A, then it is easy to define factored units mA2 etc.

**Comment by melchiorrecaruso** [comment]
With Volt I can't use SquareRoot method. I think it's missing for TRatioUnit.

**Comment by circular17** [comment]
Indeed. I have added squaring for TRatioUnit and TUnitProduct.

**Pull request closed without merging**
