### PR TITLE
Angular speed fix + heat transmission units

### PR DESCRIPTION
**Pull request by melchiorrecaruso**

### CODE REVIEW

**Comment by circular17** [comment]
I suppose it is all good. Though I am not sure why to delete the following:
```pascal
// alternate definitions
{$DEFINE LeftId:=TMeterId}{$DEFINE RightId:=THertzId}{$DEFINE ProdId:=TMeterPerSecondId}
{$DEFINE LeftQty:=TMeters}{$DEFINE RightQty:=THertz}{$DEFINE ProdQty:=TMetersPerSecond}
{$DEFINE ALT_PROD}{$i dim.pas} // m/s = m * Hz

{$DEFINE LeftId:=TMillimeterId}{$DEFINE RightId:=THertzId}{$DEFINE ProdId:=TMillimeterPerSecondId}
{$DEFINE LeftQty:=TMillimeters}{$DEFINE RightQty:=THertz}{$DEFINE ProdQty:=TMillimetersPerSecond}
{$DEFINE ALT_PROD}{$i dim.pas} // mm/s = mm * Hz
```

**Comment by circular17** [comment]
I am glad, it seems we are able to go forward with the defines. 👍

**Comment by melchiorrecaruso** [comment]
> I suppose it is all good. Though I am not sure why to delete the following: > > ```pascal > // alternate definitions > {$DEFINE LeftId:=TMeterId}{$DEFINE RightId:=THertzId}{$DEFINE ProdId:=TMeterPerSecondId} > {$DEFINE LeftQty:=TMeters}{$DEFINE RightQty:=THertz}{$DEFINE ProdQty:=TMetersPerSecond} > {$DEFINE ALT_PROD}{$i dim.pas} // m/s = m * Hz > > {$DEFINE LeftId:=TMillimeterId}{$DEFINE RightId:=THertzId}{$DEFINE ProdId:=TMillimeterPerSecondId} > {$DEFINE LeftQty:=TMillimeters}{$DEFINE RightQty:=THertz}{$DEFINE ProdQty:=TMillimetersPerSecond} > {$DEFINE ALT_PROD}{$i dim.pas} // mm/s = mm * Hz > 

I removed it because there are two operators with same parameters but different result: $[ m/s ] / [ m ] = [ Hz ] = [ rad / s ]$ I will try with NO_LEFT_DIV macro. Regards

**Comment by circular17** [comment]
Oh I understand.

**Pull request merged**
