### PR TITLE
Adding Watt, Volt

### PR DESCRIPTION
**Pull request by melchiorrecaruso**
Adding Watt
Adding Volt
Adding N/mm
Typing fix

### CODE REVIEW

**Comment by circular17** [comment]
Thanks.

There is indeed a need for additional operators because there are various way of combining the units.

I will look at it.

**Comment by melchiorrecaruso** [comment]
About Joule, two more explicit operators are needed. First one because J is N*m and m*N (this is missing), 
and second one because inside then ProductUnit class only one / operator can be.
Please check it too, Then I will add them.
Thanks

**Comment by circular17** [comment]
Hi, I am back and reading the code.

About this operator
```pascal
operator:=(const AWeight: TBaseKilograms): TGrams;
```
It is on purpose that the result is TGrams. Indeed if for some reason we have a value in TBaseKilograms, and that we need instead the base unit, as there is only one implicit conversion, we need this operator.

Maybe you had a case were you needed conversion to TKilograms. In this case, maybe we could add both operators.

About these units
```pascal
   TGramPerCubicMillimeter = specialize TFactoredDenominatorUnit<TGram, TCubicMillimeter>;
   TKilogramPerCubicMeter = specialize TRatioUnit<TBaseKilogram, TCubicMeter>;
   TKilogramPerCubicMillimeter = specialize TFactoredDenominatorUnit<TBaseKilogram, TCubicMillimeter>;
```
To have automatic conversions between them, we need TKilogram instead of TBaseKilogram. TBaseKilogram is the unit that is only needed when it is part of a special unit, like ohm or newton. Indeed these units are expressed as one symbol (omega, N) and can be factored and this time the base unit is the kilogram.

**Comment by circular17** [comment]
Changes look good to me overall. I see you've added operators to handle additional combinations of the units. It makes sense as there are various ways to combine them.

**Comment by melchiorrecaruso** [comment]
Welcome back! 

What is the plural of Siemens? If for Hertz you have used TFrequency, then now it will be TElectricalConductance.

Can I restart or You are doing othes changes ?

**Comment by circular17** [comment]
For one thing I could not put to the plural, I've named it ...Quantity. I guess it is simpler to find it this way. But your suggestion makes sense as well. I am not really settled on anything.

Yes you can continue making changes, I am not doing anything significant now. I was thinking about reorganizing the special units, there are a lot and maybe it could be split. Maybe you have an idea on that.

**Comment by melchiorrecaruso** [comment]
The plural of siemens is always siemens:

https://en.wiktionary.org/wiki/siemens

I think that nobody will find easly TElectricalConductance if all other units are named as unit+s.
And if we change the name of unit ... ?

About special unit, I think that it's needed to split the code.
About duplicates units (... Becquerel, Gray) , can we define these units as alias ? It's right to do that ?

  `TGrayIdentifier = TSievertIdentifier;`
  `TGrays = TSieverts;`

Edit: It'snt needed define TSiemens unit 

`TSiemens = specialize TRatioUnit<TAmpere, TVolt>;     `

because there aren't Siemens derived units; We can use TSiemens for quantity

` TSiemens = specialize TRatioDimensionedQuantity<TAmpere, TVolt>;`

I think we can do the same thing for Hertz.

**Comment by circular17** [comment]
Defining a type alias will give the impression of another unit but it won't be the case, it will still be displayed with the other name. I don't see an easy way to solve this, apart from defining a standalone unit TGray and provide dimension equivalence operators.

About defining units without adding an s, why not. In this case, if we have to define the unit, we can call it ...Unit. So TSiemensUnit would be the unit and TSiemens would be the quantity.

About splitting the code for special units, do you have suggestions that would make sense from a physical point of view?

**Comment by melchiorrecaruso** [comment]
Uhm .... Mechanics, Elettromagnetism and an other unit for  other units.

Here there are some useful infomations:

[https://paolofornasini.com](url)

**Comment by circular17** [comment]
Very interesting indeed
https://paolofornasini.com/international-system-of-units/

**Pull request merged**
