### PR TITLE
Added N/m, Pa, MPa and Joule

### PR DESCRIPTION
**Pull request by melchiorrecaruso**
Hello Circular,

there are some updates.

Regards

### CODE REVIEW

**Comment by circular17** [comment]
Thanks.

I reviewed the code, it looks good on the whole.

There are some things to fix regarding the operators.
```pascal
operator *(const {%H-}N: TNewtonIdentifier; const {%H-}m: TMeterIdentifier): TNewtonPerMeterIdentifier; inline;
operator *(const AForce: TNewtons; const ALength: TMeters): TNewtonsPerMeter; inline;
```
These operators would be "/" rather than "*". A mistake I also made, hence the value of doing a review, two pairs of eyes being better than one.

There is a need to define explicitly other operators to create units/quantity:

- TNewtonPerMeter / TMeterIdentifier = TPascalIdentifier
- TNewtonIdentifier * TMeterIdentifier = TJouleIdentifer

Same thing for quantities.

Regards

**Comment by circular17** [comment]
Regarding operators for mm2 and MPa, it is not necessary to define them explicitly, they will be automatically converted to m2 and Pa. You can define them though to avoid the implicit conversion and to specify the resulting unit.

**Comment by circular17** [comment]
Note: you can do the changes in your branch, the pull request will be updated automatically

**Comment by melchiorrecaruso** [comment]
Ok thanks.

**Comment by circular17** [comment]
No need to close the request

**Comment by melchiorrecaruso** [comment]
Now I'm at work , I'll make corrections in the evening.
About Pa/m2 and MPa/mm2, I have added each operator after trying to compiling the example, for fixing compilations errors.
I will check that too.

**Comment by circular17** [comment]
Yes as Pa is defined as N/m/m then one need to define extra operators for N/m2. (EDIT it was s not m)

**Comment by melchiorrecaruso** [comment]
` TNewtonPerMeter / TMeterIdentifier = TPascalIdentifier`

We could skip this because Pressure is Force/Area or create it if really needed.
What do you think ?

I wrote Pascals as N/m /m for convenience, TUnit can be manager easier than TFactoredUnit.

**Comment by circular17** [comment]
Ok, well if it makes more sense to define Pa as N/m2 then we could do that. You don't need factored units, Pa can be defined like N using TBaseKilogram.

Still, it could be a good thing to have a progression, unit by unit: N <=> N/m <=> N/m2. So if we define Pa as N/m2, we could still have some operators to handle the transition between N/m and N/m2. But that may not be very useful, I don't know.

**Comment by melchiorrecaruso** [comment]
I have see that some hour ago.
I have changed that and added density.

There are quedriced, cubed  in the code.
Can  I chance all with square, cubic and quadric ?

**Comment by circular17** [comment]
Indeed there are some more "cubed" and the like that I've not seen. Sure they can be changed. There is just the function ".Cubed" that I think need to stay that way.

I gotta go to work. I'm not sure I will be able to look this evening. Otherwise tomorrow.

**Comment by melchiorrecaruso** [comment]
Today I have a little problem with N/m unit.  I can't compile examples if there is the code line 

`Force := stiffness * length; // N = N/m * m`

The error is:

`TDimensionedQuantity<Dim.TUnitProduct
<Dim.TBaseKilogram,Dim.TRatioUnit<Dim.TRatioUnit<Dim.TMeter,Dim.TSecond>,Dim.TSecond>>>`

 `expected `

`TDimensionedQuantityProduct
<Dim.TBaseKilogram,Dim.TRatioUnit<Dim.TRatioUnit<Dim.TMeter,Dim.TSecond>,Dim.TSecond>>`

Can you help me ?
Thanks, Regards

**Comment by circular17** [comment]
I've merged and I am trying to make it work with the least amount of operators but it seems that some operations, even though as I understand it, are supposed to be defined by the generic classes, does not seem to be recognized. I am trying to understand how it is so.

**Comment by circular17** [comment]
Ok so I guess now almost all is well, just remains two missing operators, but I don't understand why.

```pascal
  writeln('Area is: ',  (force/sigma).ToString);
  writeln('Force is: ', (sigma*area).ToString);  
```

**Comment by circular17** [comment]
Force is TNewtons, sigma is TMegapascals, equivalent to TPascals. And TPascals is TNewtons/TSquareMeters.
So the operator is supposed to be overloaded by:
```pascal
class operator TRatioDimensionedQuantity./(const ANumerator: TNumeratorQuantity; const ASelf: TSelf): TDenomQuantity;
```
Which in this case is:
```pascal
class operator TPascals./(const ANumerator: TNewtons; const ASelf: TPascals): TSquareMeters;
```
Or am I missing something?

**Comment by melchiorrecaruso** [comment]
It's right. Does TNewton work correctly ?
The problem may be in TMegaPascal class.

**Comment by circular17** [comment]
I thought of TMegapascal but conversion to TPascal is automatic and it doesn't work even with an explicit conversion.

**Comment by melchiorrecaruso** [comment]
There are issues with other units also. These lines cannot to be compiled:

`time  := speed/acceleration;`
`speed := acceleration*time;`
`area  := force/pressure;`

but I didn't understand the reason.

**Comment by circular17** [comment]
Thanks for these simpler examples. I think I understand what's going on for these.

The are two different types `TRatioDimensionedQuantity<TMeter, TSecond>` and `TDimensionedQuantity<TRatioUnit<TMeter, TSecond>>`. The second one is not defined directly but it appears when deconstructing an acceleration.

Indeed an acceleration is `TRatioUnit<TMeterPerSecond, TSecond>` so the numerator is assumed to be  `TDimensionedQuantity<TMeterPerSecond>` where `TMeterPerSecond` is `TRatioUnit<TMeter, TSecond>`.

I have fixed this problem by adding an equivalence between these two types. So this compiles: 
```pascal
  speed := (km/h).From(acceleration*time);
  time.Assign(speed/acceleration);
```
One still need to write an explicit conversion or `Assign` because automatic conversion is only towards base unit and here the destination variables are in km/h and h.

Let's suppose a similar problem is going on with `TPascals`. It is defined as `TRatioDimensionedQuantity<TNewton, TSquareMeter>` so the numerator is assumed to be `TDimensionedQuantity<TUnitProduct<TBaseKilogram, TMeterPerSecondSquared>>` and the denominator `TDimensionedQuantity<TSquareUnit<TMeter>>`.

It is indeed similar, though the example doesn't compile. I could compile it by converting explicitly to base units:
```pascal
  writeln('Area is: ',  (force/TPascals(sigma)).ToString);
  writeln('Force is: ', (TPascals(sigma)*TSquareMeters(area)).ToString);
```
That's not completely satisfactory. The problem is that it would need two implicit conversions on the same value:

- initial type is `TFactoredDimensionedQuantity<TPascal, TMegapascal>`
- which can be implicitly converted to `TDimensionedQuantity<TPascal>`
- which would need then implicit conversion to `TRatioDimensionedQuantity<TNewton, TSquareMeter>`

**Comment by melchiorrecaruso** [comment]
TPascals works fine, TMegapascals not.
I have tried to fix temporary this issue with new operators but only first line can be fixed:

`area  := force/pressure; // N/MPa  `
`force := pressure*area;  // MPa/mm2`

The problem is always class mismatching.

`Operator is not overloaded: `
`"TDimensionedQuantityProduct$2$crc947E0BE2" / `
`"TFactoredDimensionedQuantity$2$crc5CBE5E98"`

`Operator is not overloaded: `
`"TFactoredDimensionedQuantity$2$crc5CBE5E98" * `
`"TFactoredSquareDimensionedQuantity$2$crcABB83A0C"`

**Comment by circular17** [comment]
It may be one of the limitations of Dim.pas, that compound units cannot be defined as factored. We could for now use factored units only for display, either by converting to MPa before display or by having the display method automatically prefix the unit instead of using E+3, E+6, etc.

**Comment by melchiorrecaruso** [comment]
It fixed temporary with this. Yesterday It didn't work, I suppose that It benefits of last updates.
[dim.zip](https://github.com/circular17/DimPas/files/10714232/dim.zip)

Please check it.

**Comment by circular17** [comment]
Interesting. Indeed, it makes sense to define MPa as N/mm2.

Is MPa a unit that is particularly used, let's say more than kPa?

**Comment by melchiorrecaruso** [comment]
In engineering MPa is more common than kPa; Yield's modulus, Shear modulus and Ultimate tensile strength are in MPa.
I think that kPa are used in pressure gauges in some country (instead of bar) ... as Japan.

**Comment by circular17** [comment]
Ok, so let's do that for now. I've applied the change of unit definition. We don't need the additional operators then, except the equivalence for mm2.

I've also added kN and then kPa as factored unit kN/m2.

So we're good. This pull request is solved.

**Comment by circular17** [comment]
I've reorganized the code, so I invite you to merge from my branch to get latest version to avoid merge conflicts.

I admit I was unsure we could make it, but we did. Thank you very much indeed.

**Comment by melchiorrecaruso** [comment]
Your welcome. I'm adding Watt and Volt.

**Comment by circular17** [comment]
I'm adding steradian, it is needed by some derived units.

**Comment by melchiorrecaruso** [comment]
Watt and Volt added.
Do I have to open a new pull request ?

**Comment by circular17** [comment]
Yes

**Pull request merged**
