### PR TITLE
Thermal radiation, linear thermal expansion and momentum units.

### PR DESCRIPTION
**Pull request by melchiorrecaruso**

### CODE REVIEW

**Comment by circular17** [comment]
Looks good. I guess am going to add defines for reciprocal quantities.

**Comment by circular17** [comment]
https://github.com/circular17/DimPas/commit/1229a69fd0fe4ba1991a4da8a036c48f6cf90566

**Comment by melchiorrecaruso** [comment]
Well done! 👍

**Comment by melchiorrecaruso** [comment]
Why are there four quantity operators inside DEF_PROD macro ? 
Three operators are enough, or not ?

**Comment by circular17** [comment]
There are only 3, the fourth is in an IFNDEF

**Comment by circular17** [comment]
I am thinking that the following units could be in derivedunits.inc instead of specialderived.inc and defined using TGram instead of TBaseKilogram.

```pascal
  // MOMENTUM & IMPULSE

  TKilogramMeterPerSecond = specialize TUnitProduct<TBaseKilogram, TMeterPerSecond>;
  TKilogramMeterPerSecondId = specialize TUnitProductId<TBaseKilogram, TMeterPerSecond>;
  TKilogramMetersPerSecond = specialize TQuantityProduct<TBaseKilogram, TMeterPerSecond>;

  // ANGULAR MOMENTUM & ANGULAR IMPULSE

  TKilogramSquareMeter = specialize TUnitProduct<TBaseKilogram, TSquareMeter>;
  TKilogramSquareMeterId = specialize TUnitProductId<TBaseKilogram, TSquareMeter>;
  TKilogramSquareMeters = specialize TQuantityProduct<TBaseKilogram, TSquareMeter>;

  TKilogramSquareMeterPerSecond = specialize TUnitProduct<TKilogramSquareMeter, TRadianPerSecond>;
  TKilogramSquareMeterPerSecondId = specialize TUnitProductId<TKilogramSquareMeter, TRadianPerSecond>;
  TKilogramSquareMetersPerSecond = specialize TQuantityProduct<TKilogramSquareMeter, TRadianPerSecond>;
```

Of course then TKilogramSquareMetersPerSecond would rather be defined as a ratio with TSecond and the definition with radian would be an alternate definition.

I am wondering about the radian unit. So we are considering that multiplying by radian removes its unit. It makes sense from the formula for the length of an arc though it is surprising.

**Comment by melchiorrecaruso** [comment]
> Why are there four quantity operators inside DEF_PROD macro ? Three operators are enough, or not ?

> There are only 3, the fourth is in an IFNDEF

It seems out IFNDEF to me.

**Comment by circular17** [comment]
```pascal
{$IFNDEF DEF_PROD}
operator /(const {%H-}AProd: ProdId; const {%H-}ARight: RightId): LeftId; inline;
{$IFDEF IMPL}begin end;{$ENDIF}
{$ENDIF} 
```
There is `{$IFNDEF DEF_PROD}` and inside `{$IFDEF IMPL}`

**Comment by melchiorrecaruso** [comment]
> Of course then TKilogramSquareMetersPerSecond would rather be defined as a ratio with TSecond and the definition with radian would be an alternate definition.

Right! Thank you for the heads-up.

> I am wondering about the radian unit. So we are considering that multiplying by radian removes its unit. It makes sense from the formula for the length of an arc though it is surprising.

Radian is like a ghost, It appears and disappears. :smile:

EDIT:

>I am thinking that the following units could be in derivedunits.inc instead of specialderived.inc and defined using TGram instead of TBaseKilogram.

I would prefer to divide the units based on the subject, mechanics, thermodynamics...
It is easier to have an overview.

**Comment by melchiorrecaruso** [comment]
> ```pascal
> {$IFNDEF DEF_PROD}
> operator /(const {%H-}AProd: ProdId; const {%H-}ARight: RightId): LeftId; inline;
> {$IFDEF IMPL}begin end;{$ENDIF}
> {$ENDIF} 
> ```
> 
> There is `{$IFNDEF DEF_PROD}` and inside `{$IFDEF IMPL}`

Yes, for Identifier, not for quantity. I have specified it in the first post.

**Comment by circular17** [comment]
Oh indeed, you're right. I've missed that.

Now I've fixed it.

**Comment by circular17** [comment]
Radian the ghost unit 😆

I understand you would prefer to divide the units based on the subject, mechanics, thermodynamics... My idea was to ensure consistency in the dependencies between units. Though it also makes sense to do the categories you propose. We could even create inc files for such categories. And so, `derivedunits.inc` and `specialderived.inc` would only contain general purpose derived units.

**Comment by melchiorrecaruso** [comment]
Yes, this is more or less what is my idea, to have a core with common unit and other units divided by subject. I agree. Please not split unit now, I have some changements to commit.

**Comment by melchiorrecaruso** [comment]
Other my considerations for you to evaluate:

I saw that you created the "DEF_POWER" macro, good. However, I would prefer it to be more modular so that I can choose which powers to create. For example, there's no need to create K2 and K3. Now I need to create rad2/s2, but I don't want cubic and quartic powers. I would prefer the functions for switching between powers to be like the standard ones, outside the classes. The same goes for trigonometric functions.

Regards

**Comment by circular17** [comment]
I am not sure what you mean by "I would prefer the functions for switching between powers to be like the standard ones, outside the classes"

Can you provide some sample code usage to show me how you would imagine it?

**Comment by melchiorrecaruso** [comment]
Yes I can. I mean simple functions:

```
function SquareRoot(const AQuantity: TSquareMeters): TMeters;
function CubicRoot(const AQuantity: TCubicMeters): TMeters;
```
...
```
function Cos(AQuantity: TRadians): double.
function ArcCos(AValue: double): TRadians.
```
Example:
```
var
  Side: TMeters;
  Area: TSquareMeters;
begin
  Side := SquareRoot(Area);
end;
```

**Comment by circular17** [comment]
Sure, those functions could be defined as well. For example, we can add root and power functions in the DEF_POWER macro.

The Cos and ArcCos functions could be added, though inverse functions like ArcCos would always return radians.

One need to check as well if those functions do not hide math functions on floats when they have the same name.

**Comment by melchiorrecaruso** [comment]
> One need to check as well if those functions do not hide math functions on floats when they have the same name.

Functions previously defined are hidden by those with the same name defined later, 
it's depends on the order of units in the "uses" clause .

Then It's needed specify the unit name for calling hidden function.

`math.ArCos(0.5)`

Regards

**Comment by circular17** [comment]
Ok. Well, in fact, thinking about it, if people are using Dim, they will be ok with having a result in radian.

**Pull request merged**
