### PR TITLE
Adding Siemens, Weber, Tesla, Henry ...

### PR DESCRIPTION
**Pull request by melchiorrecaruso**

### CODE REVIEW

**Comment by circular17** [comment]
Thanks.

Defining gray as
```pascal
TGrayIdentifier = specialize TRatioUnitIdentifier<TJoule, TBaseKilogram>
```
will indeed make it different from the sievert
```pascal
TSievertIdentifier = specialize TRatioUnitIdentifier
                                   <TSquareMeter, specialize TSquareUnit<TSecond>>
```

The symbol and name was not defined for this unit. I will add that for you.

Defining becquerel as
```pascal
TBecquerelIdentifier = specialize TReciprocalUnitIdentifier<TSecond>;
```
won't make it different form hertz. The only way I see is to define a brand new unit. That will allow to give it a name.

I suppose it makes sense to add the curie as well.

I've applied those changes.

**Comment by circular17** [comment]
https://github.com/circular17/DimPas/commit/4535d916f30ba8c2a285901e5ad4dbd362eaa52e

**Comment by melchiorrecaruso** [comment]
And now what we can do ?
Have you a roadmap ?

**Comment by circular17** [comment]
Good question. I suggest we ask the people that were interested in this package. I will do on the forum.

**Comment by melchiorrecaruso** [comment]
We can add some imperial units, inch, foot ... these can be useful.
What do you think ?

I'm using dim.pas for my application. I will not define lenghts as TMillimeters because It's not possible assign values using others length units. For example:

`millimeters_len := 10*cm;  // it isn't compiled`
`meters_len := 10*cm        // it's compiled`

The same thing for Pascal and other units.

I'm understand this only now; Dim.pas work as uunits.pas, it's needed define the variebles using the seven SI units only.
If what I have wrote it's true, I think that it's better explain that because if an user read the code and see all units defined inside,  he can misinterpret and then his code won't work.

Regards

**Comment by circular17** [comment]
Well you can do the following
```pascal
millimeters_len.Assign(10*cm);
```

Just that automatic conversion is only towards base units.

**Comment by melchiorrecaruso** [comment]
ok, thanks for suggestion.

**Pull request merged**
