### PR TITLE
Added centrifugal force units. Made some adjustment to m2/s2 unit.

### PR DESCRIPTION
**Pull request by melchiorrecaruso**
There seems to be an issue, but I couldn't identify the error. 
When I attempt to print the unit of squared angular speed , the output is wrong. 
Could you please verify it as well?

Thanks

### CODE REVIEW

**Comment by circular17** [comment]
I will have a look

**Comment by circular17** [comment]
Ok I've found a way to fix that. Now it is possible to specify that a ratio or a product is "powerable".

```pascal
type
  TMeterPerSecond = specialize TRatioUnit<TMeter, TSecond>;
  TMeterPerSecondId = specialize TPowerableRatioUnitId<TMeter, TSecond>;
  TMetersPerSecond = specialize TPowerableRatioQuantity<TMeter, TSecond>; 
```

**Comment by melchiorrecaruso** [comment]
Ok, I will look the new code.

I have found an other error:

TKilogramSquareMeterPerSecond  is a TRatioUnit not a TUnitProduct.

Bye

**Comment by circular17** [comment]
Indeed. As well I am not sure where is the other definition ([ N*m ] * [s]) here:
```pascal
{ alternative definition [ kg*m2/s ] = [ N*m ] * [s] = [ J ] * [ s ] }
{$DEFINE LeftId:=TJouleId}{$DEFINE RightId:=TSecondId}{$DEFINE ProdId:=TKilogramSquareMeterPerSecondId}
{$DEFINE LeftQty:=TJoules}{$DEFINE RightQty:=TSeconds}{$DEFINE ProdQty:=TKilogramSquareMetersPerSecond}
{$DEFINE ALT_PROD}{$i dim.pas} 
```

**Comment by melchiorrecaruso** [comment]
There isn't an other definition ($[ N*m ] * [s]$), It's just a comment.

**Comment by circular17** [comment]
Ah ok, because N*m = J, got it

**Comment by melchiorrecaruso** [comment]
I can't compile this line:

`writeln('The speed is: ', (km/h).From(speed).ToString);     `

where speed is TMetersPerSecond.

The compiler message is:

`examples.pas(210,46) Error: Incompatible type for arg no. 1: Got "TPowerableRatioQuantity<Dim.TMeter,Dim.TSecond>", expected "TRatioQuantity<Dim.TMeter,Dim.TSecond>"`

**Comment by circular17** [comment]
Hello Melchiorrecaruso!

I don't have the error, but I have added more equivalences for you. Does it fix the problem? If not, do you have changes in your code?

Regards

**Comment by melchiorrecaruso** [comment]
Hi circular!

It doesn't fix the problem and I haven't changes in my repository.
It's strange, I can compile unitOfMeasurement.lpi project but I can't compile this testcase:

```
program testcase;
uses
  Dim;
var
  speed: TMetersPerSecond;
begin
  speed := 10*(m/s);  // error
  speed := 10*(km/h);
  writeln('The speed is: ', speed.ToString);
  writeln('The speed is: ', (m/s).From(speed).ToString);
  writeln('The speed is: ', (km/h).From(speed).ToString);
  writeln;
end. 
```
Assignment doesn't work too.

EDIT: I have tried on another pc installing lazarus from scratch. The problem is the same:

```
Compile Project, Target: testcase.exe: Exit code 1, Errors: 4, Hints: 3
testcase.lpr(10,14) Error: Incompatible types: got "TRatioQuantity<Dim.TMeter,Dim.TSecond>" expected "TPowerableRatioQuantity<Dim.TMeter,Dim.TSecond>"
testcase.lpr(11,14) Error: Incompatible types: got "TFactoredRatioQuantity<Dim.TMeter,Dim.TSecond,Dim.TKiloUnit<Dim.TMeter>,Dim.THour>" expected "TPowerableRatioQuantity<Dim.TMeter,Dim.TSecond>"
testcase.lpr(14,45) Error: Incompatible type for arg no. 1: Got "TPowerableRatioQuantity<Dim.TMeter,Dim.TSecond>", expected "TRatioQuantity<Dim.TMeter,Dim.TSecond>"
dim.pas(418,20) Hint: Found declaration: class From(const TRatioQuantity$2$crcE6CC9588):<record type>; Static;
testcase.lpr(15,46) Error: Incompatible type for arg no. 1: Got "TPowerableRatioQuantity<Dim.TMeter,Dim.TSecond>", expected "TRatioQuantity<Dim.TMeter,Dim.TSecond>"
dim.pas(438,20) Hint: Found declaration: class From(const TRatioQuantity$2$crcE6CC9588):<record type>; Static;
dim.pas(418,20) Hint: Found declaration: class From(const TFactoredRatioQuantity$4$crc17F31CBE):<record type>; Static;

```
EDIT2: I'm saying something silly, but if we defined square (cubic...) units as a product, wouldn't it be simpler?
```
TSquareHenry = specialize TUnitProduct<THenry, THenry>;
TSquareHenryId = specialize TUnitProductId<THenry, THenry>;
TSquareHenrys = specialize TQuantityProduct<THenry, THenry>;

{ main definition [ H2 ] = [ H ] * [ H ] }
operator *(const {%H-}ALeftId: THenryId; const {%H-}ARightId: THenryId): TSquareHenryId;
{$IFDEF IMPL}begin end; {$ENDIF}
operator *(const ALeft: THenrys; const ARight: THenrys): TSquareHenrys; inline;
{$IFDEF IMPL}begin result.Value := ALeft.Value * ARight.Value; end; {$ENDIF}  
```

**Comment by circular17** [comment]
Oh ok I found, there was a missing "Powerable" prefix. That's fixed. Thanks for your example.

Unfortunately no we cannot define a power as a product, because the multiplication would be defined twice (left * right and right * left would be the same).

**Comment by melchiorrecaruso** [comment]
> Oh ok I found, there was a missing "Powerable" prefix. That's fixed. Thanks for your example.

You're welcome!

> Unfortunately no we cannot define a power as a product, because the multiplication would be defined twice (left * right and right * left would be the same).

We can solve it moving the one operator inside the product class into the macro and creating others macro for each powers. In any case, if the problem is fixed we can continue as it is. Thanks for bugfix.

EDIT: The problem is still present. Were you able to compile the test program on your computer?

**Comment by circular17** [comment]
Indeed, we could use the same definition. It could simplify some things. At the same time we would have various ways of defining the same unit, for example: m*(m*m) <> (m*m)*m

About the compilation problem, indeed there were other things that did not compile. As I found it a bit complicated to have both powerable and non powerable, I just made all ratios and products powerable, and it seems to compile fine.

**Comment by melchiorrecaruso** [comment]
Thanks! Now It works fine.

**Comment by melchiorrecaruso** [comment]
> Indeed, we could use the same definition. It could simplify some things. At the same time we would have various ways of defining the same unit, for example: m*(mm) \<> (mm)*m

I don't understand what you mean. Can you write an example ?

**Comment by circular17** [comment]
Sure. For example, m3 could be defined as
```pascal
type
  TCubicMeter1 = specialize TUnitProduct<specialize TUnitProduct<TMeter, TMeter>, TMeter>;
  TCubicMeter2 = specialize TUnitProduct<TMeter, specialize TUnitProduct<TMeter, TMeter>>;
```

**Comment by melchiorrecaruso** [comment]
Ok I understand.

Is an equivalence operator needed from Cubic1 to Cubic2 ?

I ask you this because every time I add a new unit or operator, 
the compilation times increase significantly. 

Regards

**Comment by circular17** [comment]
Yes there would be an equivalence operator needed.

I agree, the compilation time increases. It is getting quite long to compile. I would if this could be accelerated. Maybe using more macros overall could help. Though it is a bit contrary to the original objective I had chosen, to do as much as possible with generics.

This is a comparison that could change my initial objective.

Regards

**Comment by melchiorrecaruso** [comment]
Moving to external operators could improve speed a little bit, but not so much. 
I had significantly speed increase with FPC trunk version (3.3.1).

I currently use it.
Anyway It's nedeed to spare the operators, this is our Achilles' heel.

I'm adding last units, but I have a problem with $kg^2$.
I will send to you a new test case with next pull request.

Bye.

**Comment by circular17** [comment]
Good to know that trunk works better.

kg² may not be straightforward indeed.

Ok, bye.

**Comment by melchiorrecaruso** [comment]
Hi circular,

I think that to define kilogram in this way

```
TKilogram = {$DEFINE UNIT_OV_INTF}{$i dim.pas}
TKilogramId = specialize TUnitId<TKilogram>;
TKilograms = specialize TQuantity<TKilogram>;

TGram = {$DEFINE FACTORED_UNIT_INTF}{$i dim.pas}
TGramId = specialize TFactoredUnitId<TKilogram, TGram>;
TGrams = specialize TFactoredQuantity<TKilogram, TGram>;

TMilligram = {$DEFINE FACTORED_UNIT_INTF}{$i dim.pas}
TMilligramId = specialize TFactoredUnitId<TKilogram, TMilligram>;
TMilligrams = specialize TFactoredQuantity<TKilogram, TMilligram>;
```
can solve our problem with kilogram/basekilogram/square-kilogram.

What do you think about that ?

Regards

**Comment by circular17** [comment]
Hi!

I think that defining this way will not work with TMiliUnit etc.

I suppose a way is to define square kilogram from TBaseKilogram. So that kg²  would be used only with special units.

By the way, which unit needs square kilograms?

Regards

**Comment by melchiorrecaruso** [comment]
I didn't understand.  Can you explain better ?

We don't have to use TMilliUnit. 

We define TKilogram as base unit and others factored units (milligram gram, ton) from scratch using custom factors (like TMinute unit).

 kg2 is needed for gravitazional force

https://en.wikipedia.org/wiki/Gravitational_constant

I have tried with basekilogram but It doesn't work.
I can't calculate the force.

Regards

**Comment by circular17** [comment]
Well it is simpler to define mg as a TMilliUnit of g, etc.

Can you provide a sample program that would use the unit? I will see if I can make it work

**Comment by melchiorrecaruso** [comment]
> Well it is simpler to define mg as a TMilliUnit of g, etc.

Certainly, it feels easier to define milligram as TMilliUnit, but this simplification 
(few lines of code) in the case of kilogram comes at a cost. 
This cost is TBaseKilogram plus two bidirectional assignment operators. 
If we consider that we can't say that TMilliUnit is easier.

> Can you provide a sample program that would use the unit? I will see if I can make it work.

Sure ! I will send you a testcase soon.

**Comment by melchiorrecaruso** [comment]
TestCase attached !

[testcase.zip](https://github.com/circular17/DimPas/files/11558114/testcase.zip)

I think that for the compiler $TKilogram * TKilogram$ and $TBaseKilogram * TBaseKilogram$ are not the same thing.
For TKilogram and TBaseKilogram there are equivalence operators, for TSquareKilogram not.

**Comment by circular17** [comment]
Thanks. I see. Indeed, there is not equivalence when it comes to square units.

**Comment by circular17** [comment]
Ok I've added necessary equivalences. I've also merged the gravitational units.

One reason about not switching the definition of gram, is because it would be necessary to redefine mg, μg, ng, pg, but also mg/m³, μg/m³, ng/m³, pg/m³ etc. and all units derived from gram.

**Comment by melchiorrecaruso** [comment]
ok, I would have preferred to rewrite some units and permanently eliminate TBaseKilogram, 
but it doesn't matter. What's important is that it works.

Thanks !
Regards.

**Comment by melchiorrecaruso** [comment]
Hello circular!

I have found two bugs and attached a test case. 
I think that the problem is a sort of wrong unit conversion in both cases.

Can you check it ?  Thanks

[testcase.zip](https://github.com/circular17/DimPas/files/11568263/testcase.zip)

**Comment by circular17** [comment]
Hi Melchiorre,

I don't think I see an error here. Maybe is it about km and m unit?

**Comment by melchiorrecaruso** [comment]
Hello circular !

I have found something wrong inside indentifier class.
It's nedeed add a custom operator for factored quantity (or like some that) 
otherwise the automatic conversion from factored units  to base units does't work.
```
    {$IFNDEF FACTORED_UNIT_ID_INTF}
    class operator *(const AValue: double; const {%H-}TheUnit: TSelf): TQuantity;
    {$ENDIF}

    {$IFDEF FACTORED_UNIT_ID_INTF}
    class operator *(const AValue: double; const {%H-}TheUnit: TSelf): TBaseQuantity;
    {$ENDIF}  
```
New testcase attached:
-Testcase-1 passed
-Testcase-2 not passed

[testcase.zip](https://github.com/circular17/DimPas/files/11584671/testcase.zip)

EDIT: by using Pa.From() function
```
  force    := Pa.From((10*(Pa*s)) / (5*s))*(10*m2);
  force    := Pa.From((10*(Pa*s)) / (10*s))*area;
  force    := Pa.From(eta/(radius/speed))*area;
```
testcase-2 works. So far, I haven't understood which operator is missing, overloaded or wrong.

**Comment by circular17** [comment]
Ok I see. It is not a wrong unit conversion but that there would be two conversions needed to get to the destination unit, and it is not done automatically.

**Comment by circular17** [comment]
It is getting too slow so there are probably too many types and operators. One way to reduce them is to avoid having different types for the same thing.

One approach would be to use objet instead of record so that inheritance would be available, and then specify all types in the specialize definition:
```pascal
type
  TPascalSeconds = specialize TQuantityProduct<TPascal, TPascalId, TPascals,
                                               TSecond, TSecondId, TSeconds>;
```
But that would make very long definitions and operators would not need to be defined in objects. So that would need more macros as well.

Another approach would be to define identifiers and quantities only from the unit, simplifying the definition. Operators would then be defined as macros as well.
```pascal
type
  TPascal = specialize TRatioUnit<TNewton, TSquareMeter>;
  TPascalId = specialize TUnitId<TPascal>;
  TPascals = specialize TQuantity<TPascal>; 
```

The second option is simpler, though it would be less using generics.

> Hello circular!
> 
> I have found two bugs and attached a test case. I think that the problem is a sort of wrong unit conversion in both cases.
> 
> Can you check it ? Thanks
> 
> [testcase.zip](https://github.com/circular17/DimPas/files/11568263/testcase.zip)

By the way was this one about the same thing? I didn't understand.

**Comment by melchiorrecaruso** [comment]
Yes, It's the same thing. 

The problem is that FPC 3.2 is slow if there are many operators. 
Have you tried FPC Trunk ? It's easy install it with fpcupdeluxe.

I have already tried to delete not strictly necessary operators and units, but it isn't enough for FPC 3.2. (See my repository ADimPas). 

I think It's needed to do some testing.

**Comment by circular17** [comment]
I understand.

I was thinking about the following:
- to define unit identifiers and quantities only as TUnitId/TFactoredUnitId and TQuantity/TFactoredQuantity
- to probably define all operators with DEFINE apart from maybe factors/powers.
- maybe to give up on factored special units (kN etc.) and replace them by a value (kN would be the quantity 1000 N).

Looking at ADim, it looks that's what you did (operators are not in DEFINE but defined just for the wanted units so that's equivalent). Compile time is still very long indeed. I wonder, here every derived unit is defined explicitely, that may be a bit slower than using using compound unit types. So I would suggest to use compound units (not for identifiers and quantities though).

I need to get some rest to take care of myself so I may not progress on the project for a bit of time.

You're mentioning the version of FPC. If I understand correctly, your project compiles faster with trunk version. I prefer to avoid depending on trunk on my projects so that they would be easily available but it seems what we are trying to do is experimental.

If you're using latest FPC, you can use const parameters in generics to make the code shorter and probably faster. That was proposed by Warfley:
https://forum.lazarus.freepascal.org/index.php/topic,61958.msg467837.html#msg467837
That could be used like that:
```pascal
type TMeter = specialize TUnit<'m', 'meter'>;
type TKilometer = specialize TFactoredUnit<TMeter, 'km', 'kilometer', 1000>;
```

Regards

**Comment by melchiorrecaruso** [comment]
Thanks for suggestions, I'll try them. 
Best of luck with your care.

See you soon!
Melchiorre

**Comment by circular17** [comment]
Thank you. Best of luck with the unit

**Comment by melchiorrecaruso** [comment]
Hi circular!

I'm writing to share the results of my tests. Your reply is not needed.

**Regarding Wardley's suggestion:**

1) I have implemented it for FPC Trunk. 

Pro: 
- The code is more readable; 
- Compiling time a little bit shorter.  

Cons: 
- FPC 3.2 compatibility broken.

2) I have tried to implemented it for FPC3.2 in this way

```
{ Unit of Second }
type
  TSecondUnit = record
    const Symbol : string = 's';
    const Name   : string = 'second';
  end;
  TSeconds = specialize TQuantity<TSecondUnit>;
  TSecondId = specialize TQuantityId<TSecondUnit>;

var
  s: TSecondId;        

{ Unit of Millisecond }
type
  TMillisecondUnit = record
    const Symbol : string = 'ms';
    const Name   : string = 'millisecond';
    const Factor : double = 1E-03;
  end;
  TMillisecondId = specialize TFactoredQuantityId<TSecondUnit, TMillisecondUnit>;

var
  ms: TMillisecondId;   
```
I don't know if this is equivalent to Wardley's code, but results feel the same and this code in compatible with FPC 3.2.

**Regarding TUnitId and TFactoredUnitId:**

Another trick maybe to write only one operator for TUnitId and TFactoredUnitId instead of four operator as for TQuantity.

I have already used this trick with TFactoredUnitId, but now I'm using it for TUnitId too.
With FPC3.2 there is a significantly speed improvement.

With my notebook, now compiling times are: ~105sec with FPC3.2, ~6sec with FPC Trunk. 

Next step will be to try TRatio/TProduct class.

Regards

**Comment by circular17** [comment]
Cool. Glad to hear about your progress :)

**Comment by melchiorrecaruso** [comment]
Another idea maybe to remove all opertors for TUnitId or TFactoredUnitId if the unit has an identifier (`m2`, `N`, `Pa` ...).
For example, for square meter it's possible remove all Id operators because it's possible assign a value using `m2`.

With this trick compiling time becomes: ~85sec with FPC3.2.

Regards

**Comment by circular17** [comment]
I am not sure to understand. It seems sometimes it is useful to combine identifiers. Or is it that it remains the operators for compound unit identifiers?

**Comment by melchiorrecaruso** [comment]
I try to be more clear; The operator for compound unit identifier remains if there isn't an identifier symbol defined, otherwise it can be removed.

For example:
```
type
  TPascal = specialize TRatioUnit<TNewton, TSquareMeter>;
  TPascalId = specialize TRatioUnitId<TNewton, TSquareMeter>;
  TPascals = specialize TRatioQuantity<TNewton, TSquareMeter>;

var
  Pa: TPascalId;
```
for pressure there is a symbol identifier (var Pa), so it's possible delete all the operators for compound unit identifier and assign a quantity using the symbol identifier.

`pressure := 10*Pa;`

otherwise if the unit hasn't a symbol dentifier (like speed), it's needed mantain the first one identifier operator

```
type
  TMeterPerSecond = specialize TRatioUnit<TMeter, TSecond>;
  TMeterPerSecondId = specialize TRatioUnitId<TMeter, TSecond>;
  TMetersPerSecond = specialize TRatioQuantity<TMeter, TSecond>;
```
`operator / (const ANum: TMeterId; const ADenom: TSecondId): TMeterPerSecondId;`

and assign values using it

`speed := 10*(m/s);`

Regards

**Comment by melchiorrecaruso** [comment]
Regarding the possibility to define factored special units (kN etc.) as quantity (1000 N), I think that it's an interesting idea because we can add support for factored ratios and products without add a lot of operators. Indeed it's needed add only one operator for compound unit identifier

for product unit it's needed add this one

```
operator *(const ALeft: TQuantity; const ARight: TUnitId): TProductQuantity;
begin
  result.Value := ALeft.Value;
end;
```

for ratio unit it's needed add this one

```
operator /(const ANum: TQuantity; const ADenom: TUnitId): TRatioQuantity;
begin
  result.Value := ANum.Value;
end;
```
Moreover, it's needed remove brackets for assinging a quantity, for example:

```
speed := 10*m/s;     // not speed := 10*(m/s);
speed := 10*km/hour; // not speed := 10*(km/hour);
speed := 10*cm/s;    // not speed := 10*(cm/s);
```

EDIT: I have update my ADim unit so you can read the code and understand better.

**Comment by circular17** [comment]
It all make sense. I would still think that in some cases it is useful to have the compound operator, because sometimes, units are written like N/m2*... even though it is not Pascal, it can be an intermediate unit.

Removing brackets around `m/s` for example looks nice, though I wonder how the compiler optimizes this. I guess it may copy the value. So that would be little drawback of performance, but that's a detail now, considering the rest.

**Comment by melchiorrecaruso** [comment]
> It all make sense. I would still think that in some cases it is useful to have the compound operator, because sometimes, units are written like N/m2*... even though it is not Pascal, it can be an intermediate unit.

I'm not sure I understand, can you write an example ?

I have made some more experiments this morning defining all unit as factored unit.

```
type
  { Unit of Second}
  TSecondUnit = record
    const Symbol = 's';
    const Name   = 'second';
    const Factor = 1;
  end;
  TSeconId = specialize TUnitId<TSecondUnit>;

const
  s: specialize TQuantity<TSecondUnit> = (FValue: TSecondUnit.Factor);
```

This way I removed all the identifier operators. 
I did this test just to envaluate the best build time for FPC 3.2.

The result was ~65sec for example.lpi project, the build time is still too high.
I think that FPC is not fast enough for DimPas project, It's needed hope for next FPC release.

Regards

**Comment by circular17** [comment]
Yes, unfortunately, that seems to be the case.

I am not sure I have an example. Let's say someone wants to write dynamic viscosity as N/m2*s. I don't know if that really makes sense though.

**Comment by melchiorrecaruso** [comment]
> I am not sure I have an example. Let's say someone wants to write dynamic viscosity as N/m2*s. I don't know if that really makes sense though.

Ok clear. In reality this limitation was overcome when I wrote about operators for factored ratios/products.

The new "mixed" operators

```
operator *(const ALeft: TQuantity; const ARight: TUnitId): TQuantity;
operator /(const ANum: TQuantity; const ADenom: TUnitId): TQuantity;
```

work fine with factored and un-factored ratios/products. :tada:
The only rule is not to use brackets.

Regards

EDIT: In reality what I wrote is not always true. The possibility to explode units depends on the intermediate units, if the intermediate units are defined or not. With `Pa*s` it's work.

Regard

**Comment by circular17** [comment]
Ok I understand. Sounds very good.

Have a good evening.

**Comment by melchiorrecaruso** [comment]
Hello Circular!

How are you? I hope you're doing well.
I've made some modifications to the ADimPas project, and I would like to share them with you:

- Added almost all the units and alternative definitions that I found on the HyperPhysics website. 
  Initially, I had doubts about the feasibility of this project because I had no idea how many units we 
  would have to define. Now I'm more confident, and there shouldn't be many units left to add.
  The HyperPhysics and OpenStax websites are excellent reference points.

- Added identifiers for the factored quantities (from tera to pico) for all the units defined so far.

- Regarding equivalent units (for example, Sv=Gy=J/kg=m2/s2 or J = N*m), 
  instead of using assignment operators that slow down the compilation,
  I have defined these units as aliases, for example
```
type
  { Unit of NewtonMeter }
  TNewtonMeterUnit = record
    const Symbol = 'N.m';
    const Name   = 'newton meter';
  end;
  TNewtonMeters = specialize TQuantity<TJouleUnit>;
  TNewtonMeterUnitId = specialize TUnitId<TJouleUnit>;  
``` 
  and then added a helper function to the base quantity
```
type
  TJouleHelper = record helper for TJoules
    function ToNewtonMeter: specialize TQuantity<TNewtonMeterUnit>;
end;
```
  In this way, the operators continue to work, and the results can be printed using the symbol "N.m." 
  All of this is achieved without using assignment operators.

- I have written a new function, ToString, which allows printing results by changing the unit prefixes. 
   For example:
```
writeln('The speed is: ', (5*km/hr).ToString(5,0,[]));             // output will be: The speed is: 1,3889 m/s;
writeln('The speed is: ', (5*km/hr).ToString(5,0,[pKilo, pHour])); // output will be: The speed is: 5 km/h;
```
  With this function, we can print the results by changing the prefixes (tera, mega, ... pico) 
  of the units without the need to define the factored units.

- Removed the TFactoredUnitId type; now I only use TQuantity and TUnitId.

I'm really pleased with the result because ADimPas does everything I expect it to do.
I hope these solutions can also be used for the DimPas project.

Regards

**Comment by circular17** [comment]
Hello Melchiorre,

I am alright, enjoying some vacation, but well always doing some things.

Well done. Congratulations on finishing the whole thing!

Good to know that assignments slow down compilation. So limiting those solves the compilation time problem?

Regards

**Comment by melchiorrecaruso** [comment]
Thank you!

No, unfortunately, I had removed assignment operators right from the beginning. 
Now I have just found a way to avoid adding them.

Furthermore, I have added some new units (~10) and alternative definitions (~30), 
so the compilation time has further increased from 85s to 185s for FPC3.2 (6.5s for FPC3.3.1).

I don't want to take up any more of your time. 
Enjoy your vacation!

Regards

**Comment by circular17** [comment]
Oh ok I understand.

Thanks for taking care of my time. That's ok to chat with you, it doesn't take up much time and energy.

So thanks for your messages.

Goodnight

**Comment by melchiorrecaruso** [comment]
Hello Circular!

I'm testing ADimPas in my program for mechanical spring design, and I have realized that it is necessary to add this new function to the TQuantity class:

`function TQuantity.Value(const Prefixes: TPrefixes): double;`

With this function, it's possible to convert the value of FValue based on the prefixes.
I use this function to pass the calculation results to a TChart class that creates graphs.
This function might be slow, but I haven't been able to improve it further.

Another consideration relates to the factored quantities (kg, km, kPa...). 
The Pascal language is not case-sensitive, so "MPa" and "mPa" are the same thing.
This could create confusion for a user. I myself forgot that I had defined mega-pascal as "megaPa" and I continued to use "MPa" thinking it was mega, but it was actually milli. :smiley:

Regards

**Comment by circular17** [comment]
Hi !

It makes sense to have a function to convert to another prefix as it is used for display as well. I look at the function, sure, it is not very much optimized. I am not sure about the principle. Wouldn't it make more sense to convert to a base unit without prefixes, and then just multiply by the wanted factor?

It is true that there are some ambiguities without case-sensitivity. Though I would believe that if one is used, the other is not, because not all the range is used for one unit, some units being "small" and thus needing big factors and vice versa. Or for example for meters, we use mm (millimeter) but never Mm (megameter) and instead rather scientific notation (with km or m as base).

Regards

**Comment by melchiorrecaruso** [comment]
To determine the wanted factor, it's needed to multiply and divide the prefixes based on how the unit is constructed and consider any powers.

Currently, this operation is performed at runtime, and there are also special cases to handle for the kilogram and the second. 
That's why it is structured in this way.
Now, I am trying to change my approach.

I'll keep you updated.

Regards.

EDIT: I think this way will be faster even though there's more code to write.

```
interface
...
type
  { Unit of MeterPerSecond }
  TMeterPerSecondUnit = record
    class function Symbol (const APrefixes: TPrefixes): string; static;
    class function Name   (const APrefixes: TPrefixes): string; static;
    class function Convert(const AValue: double; const APrefixes: TPrefixes): double; static;
  end;
  TMetersPerSecond = specialize TQuantity<TMeterPerSecondUnit>;
  TMeterPerSecondUnitId = specialize TUnitId<TMeterPerSecondUnit>;  
...
implementation

{ Unit of MeterPerSecond }

class function TMeterPerSecondUnit.Symbol(const APrefixes: TPrefixes): string; static;
begin
  if Length(APrefixes) = 2 then
    result := Format('%sm/%ss', [PrefixTable[APrefixes[0]].Symbol, PrefixTable[APrefixes[1]].Symbol])
  else
    result := 'm/s';
end;

class function TMeterPerSecondUnit.Name(const APrefixes: TPrefixes): string; static;
begin
  if Length(APrefixes) = 2 then
    result := Format('%smeter per %ssecond', [PrefixTable[APrefixes[0]].Name, PrefixTable[APrefixes[1]].Name])
  else
    result := 'meter per second';
end;

class function TMeterPerSecondUnit.Convert(const AValue: double; const APrefixes: TPrefixes): double; static;
begin
  if Length(APrefixes) = 2 then
    result := AValue / (PrefixTable[APrefixes[0]].Factor / PrefixTable[APrefixes[1]].Factor)
  else
    result := AValue;
end; 
...
```
Updated ADimPas.
Regards

EDIT2: I would add the check for each prefix to skip operations with a factor of 1:
```
class function TMeterPerSecondUnit.Convert(const AValue: double; const {%H-}APrefixes: TPrefixes): double; static;
begin
  result := AValue;
  if Length(APrefixes) = 2 then
  begin
    if (APrefixes[0] <> pNone) then result := result / PrefixTable[APrefixes[0]].Factor;
    if (APrefixes[1] <> pNone) then result := result * PrefixTable[APrefixes[1]].Factor;
  end;
end;  
```

**Pull request merged**
